# Generated by Django 5.0 on 2023-12-12 12:35

import planetarium.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='image',
            field=models.ImageField(null=True, upload_to=planetarium.utils.show_image_file_path),
        ),
    ]
